In [2]:
import pandas as pd

# Series التسلسل

In [5]:
data=pd.Series([1,2,33,4,5])
data1=pd.Series(['a','b','c','d',1,2,3,4,5])
data
data1

0    a
1    b
2    c
3    d
4    1
5    2
6    3
7    4
8    5
dtype: object

In [5]:
data.values

array([ 1,  2, 33,  4,  5])

In [23]:
data1

0    a
1    b
2    c
3    d
4    1
5    2
6    3
7    4
8    5
dtype: object

In [24]:
data1.index

RangeIndex(start=0, stop=9, step=1)

In [6]:
data1.keys()

RangeIndex(start=0, stop=9, step=1)

In [33]:
S1=pd.Series(['Ahmed','Samy','Mohamed','Mohamed2'],index=['a','b','c','d'])

In [34]:
S1

a       Ahmed
b        Samy
c     Mohamed
d    Mohamed2
dtype: object

In [36]:
data=pd.Series({'Ahmed':1,'Mohamed':2,'Mahmoud':3,'Samy':4})
data

Ahmed      1
Mohamed    2
Mahmoud    3
Samy       4
dtype: int64

In [7]:
list1=pd.Index([1,2,34,5,6,7,88,99])
list2=pd.Index([1,3,4])

In [9]:
list1.Index

AttributeError: 'Index' object has no attribute 'Index'

In [41]:
list2

Index([1, 3, 4], dtype='int64')

In [45]:
list1.intersection(list2)   ايجاد العامل المشترك

Index([1], dtype='int64')

# Data Frame

In [47]:
import numpy as np

In [48]:
Array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
Array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
pd.DataFrame(Array1)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [52]:
IndexNum=['a','b','c']
ColName= ['Num1','Num2','Num3']
pd.DataFrame(Array1,index=IndexNum,columns=ColName)

   Num1  Num2  Num3
a     1     2     3
b     4     5     6
c     7     8     9

In [7]:
target=pd.Series({'Employe1':3, 'Employe2':5, 'Employe3':7, 'Employe4':4, 'Employe5':6})
attend=pd.Series({'Employe1':3, 'Employe2':5, 'Employe3':7, 'Employe4':4, 'Employe5':6})
attitude=pd.Series ({'Employe1':3, 'Employe2':5, 'Employe3':7, 'Employe4':4, 'Employe5':6})
aaA=pd.Series({'Employe1':3, 'Employe2':5, 'Employe3':7, 'Employe4':4, 'Employe5':6})

In [9]:
Aprisal=pd.DataFrame=({'Target':target,'Attend':attend, 'Attitude':attitude, 'aaA':aaA})
Aprisal

{'Target': Employe1    3
 Employe2    5
 Employe3    7
 Employe4    4
 Employe5    6
 dtype: int64,
 'Attend': Employe1    3
 Employe2    5
 Employe3    7
 Employe4    4
 Employe5    6
 dtype: int64,
 'Attitude': Employe1    3
 Employe2    5
 Employe3    7
 Employe4    4
 Employe5    6
 dtype: int64,
 'aaA': Employe1    3
 Employe2    5
 Employe3    7
 Employe4    4
 Employe5    6
 dtype: int64}

In [12]:
Aprisal['Target']

Employe1    3
Employe2    5
Employe3    7
Employe4    4
Employe5    6
dtype: int64

## Read Data

In [41]:
pd.read_excel(r'‪D:مراجغة.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: '\u202aD:مراجغة.xlsx'

In [18]:
path=(r'‪C:\Users\maged\Downloads\مراجغة.xlsx')
print (path)

‪C:\Users\maged\Downloads\مراجغة.xlsx

In [21]:
import os 
path = ‪r 'C:\Users\maged\Downloads\مراجغة.xlsx'
print(path)
print(os.path.exists(path))

SyntaxError: invalid non-printable character U+202A (2625350778.py, line 2)

In [22]:
path = ‪'C:\Users\maged\Downloads\مراجغة.xlsx'

SyntaxError: invalid non-printable character U+202A (2434377574.py, line 1)

In [35]:
import os
print(os.path.exists(r'D:\مراجعة.xlsx'))

False

In [25]:
import os
print(os.listdir())

['.anaconda', '.conda', '.continuum', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.virtual_documents', 'anaconda3', 'anaconda_projects', 'AppData', 'Application Data', 'Class 2.ipynb', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'Favorites', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'New NoteBook', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{02cdd554-7ea6-11f0-add0-925a2006d391}.TM.blf', 'NTUSER.DAT{02cdd554-7ea6-11f0-add0-925a2006d391}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{02cdd554-7ea6-11f0-add0-925a2006d391}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'Numpy .ipynb', 'OneDrive', 'Pandas.ipynb', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Try EXP.ipynb', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Videos']

In [36]:
import os
print(os.listdir(r'D:\\'))

['$RECYCLE.BIN', 'AssignmentSolution.sql', 'Bread and Rusk LOGO.jpeg', 'breadnrusk.ca.txt', 'Gallery2', 'Images and Videos', 'Internet.Download.Manager.6.38.Build15', 'ItiDiagram.png', 'LOGO.enc', 'New folder', 'Our Photos', 'PDF', 'System Volume Information', 'TRAINING', 'word', 'WORK', 'لوحة التحكم (version 1).xlsx', 'لوحة التحكم.xlsx', 'مراجغة.xlsx']

In [39]:
import pandas as pd
df = pd.read_excel(r'D:\مراجعه.xlsx')
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\مراجعه.xlsx'

In [42]:
import glob
print(glob.glob(r'D:\*.xlsx'))

['D:\\لوحة التحكم (version 1).xlsx', 'D:\\لوحة التحكم.xlsx', 'D:\\مراجغة.xlsx']

In [43]:
import glob
print(repr(glob.glob(r'D:\*.xlsx')[2]))

'D:\\مراجغة.xlsx'

In [45]:
import os 
print(os.path.exists(r'D:\مراجغه.xlsx'))
print(os.path.isfile(r'D:\مراجغه.xlsx'))

False
False

In [8]:
df = pd.read_excel(r'‪D:\Rev.xlsx')

OSError: [Errno 22] Invalid argument: '\u202aD:\\Rev.xlsx'

In [11]:
df = pd.read_excel("D:/Rev.xlsx")

In [12]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,نسبة المبيعات,نوع العميل,المنطقة,صافي المبيعات,العميل
5,NaN,NaN,NaN,NaN,0.068,عميل قوي,الجيزة,10320,هشام فتحي
6,NaN,NaN,NaN,NaN,0.042,عميل عادي,البحيرة,6450,مصطفي يسري
7,NaN,NaN,NaN,NaN,0.045,عميل عادي,المنصورة,6880,ايمن صادق
8,NaN,NaN,NaN,NaN,0.09,عميل قوي,القاهرة,13760,احمد ممدوح
9,NaN,NaN,NaN,NaN,0.18,عميل مهم,اسوان,27520,مريم محمود
10,NaN,NaN,NaN,NaN,0.394,عميل مهم,المنيا,60200,سيد عفيفي
11,NaN,NaN,NaN,NaN,0.023,عميل عادي,القاهرة,3440,اشرف محمود
12,NaN,NaN,NaN,NaN,0.017,عميل عادي,البحيرة,2580,اسعد شريف
13,NaN,NaN,NaN,NaN,0.051,عميل قوي,المنصورة,7740,مرتضي المسيري
14,NaN,NaN,NaN,NaN,0.09,عميل قوي,الشرقية,13760,سارة الشافعي

In [20]:
fx = pd.read_excel(r"‪D:\لوحة التحكم.xlsx")

OSError: [Errno 22] Invalid argument: '\u202aD:\\لوحة التحكم.xlsx'

In [10]:
fx

NameError: name 'fx' is not defined

In [21]:
fx = pd.read_excel(r"D:\لوحة التحكم.xlsx")

In [19]:
fx

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,المندوب,التاريخ,المنطقة,الصافي,الضريبة,القيمة,البيان,اسم العميل,NaN,NaN,NaN
1,NaN,محمد,2021-01-14 00:00:00,الجيزة,8600,1400,10000,فاتورة,هشام فتحي,NaN,NaN,NaN
2,NaN,مصطفي,2021-02-14 00:00:00,البحيرة,6020,980,7000,فاتورة,مصطفي يسري,NaN,NaN,NaN
3,NaN,نور,2021-03-14 00:00:00,المنصورة,4300,700,5000,فاتورة,ايمن صادق,NaN,NaN,NaN
4,NaN,سيد,2021-04-14 00:00:00,القاهرة,12900,2100,15000,فاتورة,احمد ممدوح,NaN,NaN,NaN
5,NaN,محمد,2021-05-14 00:00:00,اسوان,17200,2800,20000,فاتورة,مريم محمود,NaN,NaN,NaN
6,NaN,مصطفي,2021-06-14 00:00:00,المنيا,13760,2240,16000,فاتورة,سيد عفيفي,NaN,NaN,1.0
7,NaN,نور,2021-07-14 00:00:00,القاهرة,3440,560,4000,فاتورة,اشرف محمود,NaN,NaN,1.0
8,NaN,سيد,2021-08-14 00:00:00,الجيزة,1720,280,2000,فاتورة,ايمن صادق,NaN,NaN,1.0
9,NaN,محمد,2021-09-14 00:00:00,البحيرة,2580,420,3000,فاتورة,اسعد شريف,NaN,NaN,1.0
10,NaN,مصطفي,2021-10-14 00:00:00,المنصورة,7740,1260,9000,فاتورة,مرتضي المسيري,NaN,NaN,1.0
11,NaN,نور,2021-11-14 00:00:00,الشرقية,13760,2240,16000,فاتورة,سارة الشافعي,NaN,NaN,1.0
12,NaN,سيد,2021-12-14 00:00:00,الشرقية,8600,1400,10000,فاتورة,مريم محمود,NaN,NaN,1.0
13,NaN,سيد,2021-06-15 00:00:00,القاهرة,-860,140,1000,مرتجع,احمد ممدوح,NaN,NaN,1.0
14,NaN,محمد,2021-06-16 00:00:00,الجيزة,-1720,280,2000,خصم,هشام فتحي,NaN,NaN,1.0
15,NaN,مصطفي,2021-06-17 00:00:00,البحيرة,-430,70,500,خصم,مصطفي يسري,NaN,NaN,1.0
16,NaN,نور,2021-06-18 00:00:00,المنصورة,-860,140,1000,مرتجع,ايمن صادق,NaN,NaN,1.0
17,NaN,محمد,2021-06-21 00:00:00,اسوان,-1720,280,2000,مرتجع,مريم محمود,NaN,NaN,1.0
18,NaN,نور,2021-05-14 00:00:00,المنصورة,4300,700,5000,فاتورة,ايمن صادق,NaN,NaN,1.0

In [17]:
dx

NameError: name 'dx' is not defined

In [22]:
path = "‪D:\لوحة التحكم.xlsx"
print(repr(path))

'\u202aD:\\لوحة التحكم.xlsx'

In [24]:
yo= pd.read_excel(r"‪C:\Users\maged\Downloads\Sales_Data_Training.xlsx")

OSError: [Errno 22] Invalid argument: '\u202aC:\\Users\\maged\\Downloads\\Sales_Data_Training.xlsx'

In [12]:
yo = pd.read_excel(r"C:\Users\maged/Downloads\Sales_Data_Training.xlsx")

In [13]:
yo

,InvoiceID,Date,Customer,City,Salesperson,Category,Product,Quantity,UnitPrice,Discount,Total,Payment
0,1001,2025-12-19,Customer 91,Cairo,Omar,Home,Chair,6,1493,0.10,8062.20,Card
1,1002,2025-08-13,Customer 71,Alex,Omar,Clothes,Pants,9,835,0.00,7515.00,Cash
2,1003,2025-08-18,Customer 99,Tanta,Ahmed,Home,Lamp,5,884,0.15,3757.00,Card
3,1004,2025-11-05,Customer 94,Cairo,Youssef,Electronics,Laptop,5,2313,0.15,9830.25,Wallet
4,1005,2025-08-31,Customer 54,Giza,Mona,Home,Lamp,7,2398,0.15,14268.10,Wallet
...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,2025-12-02,Customer 42,Tanta,Sara,Clothes,Pants,2,2796,0.15,4753.20,Cash
496,1497,2025-06-16,Customer 37,Giza,Youssef,Clothes,Shirt,8,2397,0.00,19176.00,Card
497,1498,2025-11-07,Customer 40,Cairo,Omar,Home,Table,4,489,0.05,1858.20,Card
498,1499,2025-01-03,Customer 39,Alex,Mona,Clothes,Shirt,1,1216,0.15,1033.60,Card
499,1500,2025-09-05,Customer 70,Giza,Mona,Electronics,Laptop,3,1534,0.10,4141.80,Card

In [27]:
xs = pd.read_excel(r"C:\Users\maged\Downloads\Sales_Data_Training.xlsx")

In [5]:
yo.head()

,InvoiceID,Date,Customer,City,Salesperson,Category,Product,Quantity,UnitPrice,Discount,Total,Payment
0,1001,2025-12-19,Customer 91,Cairo,Omar,Home,Chair,6,1493,0.10,8062.20,Card
1,1002,2025-08-13,Customer 71,Alex,Omar,Clothes,Pants,9,835,0.00,7515.00,Cash
2,1003,2025-08-18,Customer 99,Tanta,Ahmed,Home,Lamp,5,884,0.15,3757.00,Card
3,1004,2025-11-05,Customer 94,Cairo,Youssef,Electronics,Laptop,5,2313,0.15,9830.25,Wallet
4,1005,2025-08-31,Customer 54,Giza,Mona,Home,Lamp,7,2398,0.15,14268.10,Wallet

In [6]:
yo.tail()

,InvoiceID,Date,Customer,City,Salesperson,Category,Product,Quantity,UnitPrice,Discount,Total,Payment
495,1496,2025-12-02,Customer 42,Tanta,Sara,Clothes,Pants,2,2796,0.15,4753.2,Cash
496,1497,2025-06-16,Customer 37,Giza,Youssef,Clothes,Shirt,8,2397,0.00,19176.0,Card
497,1498,2025-11-07,Customer 40,Cairo,Omar,Home,Table,4,489,0.05,1858.2,Card
498,1499,2025-01-03,Customer 39,Alex,Mona,Clothes,Shirt,1,1216,0.15,1033.6,Card
499,1500,2025-09-05,Customer 70,Giza,Mona,Electronics,Laptop,3,1534,0.10,4141.8,Card

In [32]:
yo.sample(22)

,InvoiceID,Date,Customer,City,Salesperson,Category,Product,Quantity,UnitPrice,Discount,Total,Payment
287,1288,2025-02-01,Customer 61,Giza,Mona,Home,Table,4,1295,0.10,4662.0,Wallet
56,1057,2025-04-15,Customer 62,Mansoura,Youssef,Clothes,Pants,9,937,0.10,7589.7,Card
469,1470,2025-08-06,Customer 101,Tanta,Sara,Clothes,Pants,7,2818,0.10,17753.4,Cash
290,1291,2025-12-25,Customer 81,Mansoura,Mona,Electronics,Mouse,5,84,0.05,399.0,Cash
53,1054,2025-08-12,Customer 22,Alex,Omar,Electronics,Keyboard,2,902,0.15,1533.4,Card
232,1233,2025-04-05,Customer 1,Tanta,Sara,Home,Lamp,2,1021,0.10,1837.8,Cash
1,1002,2025-08-13,Customer 71,Alex,Omar,Clothes,Pants,9,835,0.00,7515.0,Cash
119,1120,2025-09-22,Customer 41,Tanta,Ahmed,Electronics,Keyboard,8,300,0.05,2280.0,Cash
45,1046,2025-05-19,Customer 34,Alex,Sara,Clothes,Jacket,1,2540,0.15,2159.0,Card
129,1130,2025-11-18,Customer 91,Giza,Youssef,Clothes,Shirt,5,2328,0.10,10476.0,Cash
472,1473,2025-10-10,Customer 88,Mansoura,Ahmed,Clothes,Jacket,2,105,0.10,189.0,Wallet
136,1137,2025-11-05,Customer 48,Giza,Mona,Electronics,Laptop,8,1832,0.05,13923.2,Wallet
293,1294,2025-09-22,Customer 91,Tanta,Sara,Home,Table,10,447,0.10,4023.0,Card
78,1079,2025-05-07,Customer 11,Mansoura,Ahmed,Clothes,Pants,9,1524,0.10,12344.4,Card
312,1313,2025-09-11,Customer 21,Cairo,Sara,Home,Table,4,1847,0.05,7018.6,Card
147,1148,2025-08-13,Customer 44,Alex,Youssef,Clothes,Pants,3,1476,0.10,3985.2,Cash
153,1154,2025-04-22,Customer 69,Cairo,Omar,Electronics,Laptop,3,247,0.00,741.0,Cash
124,1125,2025-12-25,Customer 29,Alex,Mona,Electronics,Keyboard,8,1401,0.10,10087.2,Cash
429,1430,2025-08-08,Customer 42,Cairo,Youssef,Electronics,Keyboard,8,1421,0.05,10799.6,Cash
182,1183,2025-06-02,Customer 79,Cairo,Sara,Home,Table,4,1189,0.00,4756.0,Card
420,1421,2025-06-11,Customer 30,Cairo,Omar,Home,Table,3,1002,0.15,2555.1,Wallet
289,1290,2025-11-12,Customer 95,Tanta,Mona,Electronics,Keyboard,4,2599,0.10,9356.4,Card

# Explore

In [33]:
yo.shape  معناها هات عدد الصفوف وعدد الاعمدة

(500, 12)

In [34]:
yo.info

<bound method DataFrame.info of      InvoiceID       Date     Customer   City Salesperson     Category  \
0         1001 2025-12-19  Customer 91  Cairo        Omar         Home
1         1002 2025-08-13  Customer 71   Alex        Omar      Clothes
2         1003 2025-08-18  Customer 99  Tanta       Ahmed         Home
3         1004 2025-11-05  Customer 94  Cairo     Youssef  Electronics
4         1005 2025-08-31  Customer 54   Giza        Mona         Home
..         ...        ...          ...    ...         ...          ...
495       1496 2025-12-02  Customer 42  Tanta        Sara      Clothes
496       1497 2025-06-16  Customer 37   Giza     Youssef      Clothes
497       1498 2025-11-07  Customer 40  Cairo        Omar         Home
498       1499 2025-01-03  Customer 39   Alex        Mona      Clothes
499       1500 2025-09-05  Customer 70   Giza        Mona  Electronics

    Product  Quantity  UnitPrice  Discount     Total Payment
0     Chair         6       1493      0.10   8062.20    Card
1     Pants         9        835      0.00   7515.00    Cash
2      Lamp         5        884      0.15   3757.00    Card
3    Laptop         5       2313      0.15   9830.25  Wallet
4      Lamp         7       2398      0.15  14268.10  Wallet
..      ...       ...        ...       ...       ...     ...
495   Pants         2       2796      0.15   4753.20    Cash
496   Shirt         8       2397      0.00  19176.00    Card
497   Table         4        489      0.05   1858.20    Card
498   Shirt         1       1216      0.15   1033.60    Card
499  Laptop         3       1534      0.10   4141.80    Card

[500 rows x 12 columns]>

In [36]:
yo.describe()

,InvoiceID,Date,Quantity,UnitPrice,Discount,Total
count,500.000000,500,500.000000,500.000000,500.000000,500.000000
mean,1250.500000,2025-06-28 04:04:48.000000256,5.548000,1530.340000,0.073900,7887.404100
min,1001.000000,2025-01-01 00:00:00,1.000000,57.000000,0.000000,108.000000
25%,1125.750000,2025-03-26 00:00:00,3.000000,769.750000,0.050000,2523.012500
50%,1250.500000,2025-06-25 00:00:00,5.000000,1514.500000,0.050000,6211.125000
75%,1375.250000,2025-09-27 06:00:00,8.000000,2328.000000,0.100000,11443.750000
max,1500.000000,2025-12-31 00:00:00,10.000000,3000.000000,0.150000,28150.000000
std,144.481833,NaN,2.760242,873.398256,0.055135,6435.175262

In [8]:
yo.corr(numeric_only=True)

           InvoiceID  Quantity  UnitPrice  Discount     Total
InvoiceID   1.000000 -0.009532  -0.003048 -0.002761 -0.019042
Quantity   -0.009532  1.000000  -0.001282 -0.053313  0.608021
UnitPrice  -0.003048 -0.001282   1.000000 -0.039311  0.704506
Discount   -0.002761 -0.053313  -0.039311  1.000000 -0.143108
Total      -0.019042  0.608021   0.704506 -0.143108  1.000000

In [39]:
yo.corr(numeric_only=True)

           InvoiceID  Quantity  UnitPrice  Discount     Total
InvoiceID   1.000000 -0.009532  -0.003048 -0.002761 -0.019042
Quantity   -0.009532  1.000000  -0.001282 -0.053313  0.608021
UnitPrice  -0.003048 -0.001282   1.000000 -0.039311  0.704506
Discount   -0.002761 -0.053313  -0.039311  1.000000 -0.143108
Total      -0.019042  0.608021   0.704506 -0.143108  1.000000

In [10]:
yo.isnull()

,InvoiceID,Date,Customer,City,Salesperson,Category,Product,Quantity,UnitPrice,Discount,Total,Payment
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
yo.isnull().sum()

InvoiceID      0
Date           0
Customer       0
City           0
Salesperson    0
Category       0
Product        0
Quantity       0
UnitPrice      0
Discount       0
Total          0
Payment        0
dtype: int64

# Loc/ILoc

In [20]:
yo.loc[:9, "Date":"Salesperson"]

        Date      Customer      City Salesperson
0 2025-12-19   Customer 91     Cairo        Omar
1 2025-08-13   Customer 71      Alex        Omar
2 2025-08-18   Customer 99     Tanta       Ahmed
3 2025-11-05   Customer 94     Cairo     Youssef
4 2025-08-31   Customer 54      Giza        Mona
5 2025-06-14   Customer 95      Giza        Sara
6 2025-11-16  Customer 101  Mansoura     Youssef
7 2025-08-01  Customer 115     Cairo       Ahmed
8 2025-10-07   Customer 15      Alex     Youssef
9 2025-04-02   Customer 93      Alex        Sara

In [21]:
yo.iloc[:9,1:4]

        Date      Customer      City
0 2025-12-19   Customer 91     Cairo
1 2025-08-13   Customer 71      Alex
2 2025-08-18   Customer 99     Tanta
3 2025-11-05   Customer 94     Cairo
4 2025-08-31   Customer 54      Giza
5 2025-06-14   Customer 95      Giza
6 2025-11-16  Customer 101  Mansoura
7 2025-08-01  Customer 115     Cairo
8 2025-10-07   Customer 15      Alex

# ملحوظة: -1 معناها العمود الأخير

In [23]:
yo.iloc[:10,0:-1]

,InvoiceID,Date,Customer,City,Salesperson,Category,Product,Quantity,UnitPrice,Discount,Total
0,1001,2025-12-19,Customer 91,Cairo,Omar,Home,Chair,6,1493,0.10,8062.20
1,1002,2025-08-13,Customer 71,Alex,Omar,Clothes,Pants,9,835,0.00,7515.00
2,1003,2025-08-18,Customer 99,Tanta,Ahmed,Home,Lamp,5,884,0.15,3757.00
3,1004,2025-11-05,Customer 94,Cairo,Youssef,Electronics,Laptop,5,2313,0.15,9830.25
4,1005,2025-08-31,Customer 54,Giza,Mona,Home,Lamp,7,2398,0.15,14268.10
5,1006,2025-06-14,Customer 95,Giza,Sara,Electronics,Mouse,1,2073,0.15,1762.05
6,1007,2025-11-16,Customer 101,Mansoura,Youssef,Home,Table,7,494,0.05,3285.10
7,1008,2025-08-01,Customer 115,Cairo,Ahmed,Home,Lamp,6,676,0.10,3650.40
8,1009,2025-10-07,Customer 15,Alex,Youssef,Clothes,Jacket,9,595,0.05,5087.25
9,1010,2025-04-02,Customer 93,Alex,Sara,Home,Table,2,2325,0.15,3952.50

In [24]:
yo.iloc[:10,1:-1]

,Date,Customer,City,Salesperson,Category,Product,Quantity,UnitPrice,Discount,Total
0,2025-12-19,Customer 91,Cairo,Omar,Home,Chair,6,1493,0.10,8062.20
1,2025-08-13,Customer 71,Alex,Omar,Clothes,Pants,9,835,0.00,7515.00
2,2025-08-18,Customer 99,Tanta,Ahmed,Home,Lamp,5,884,0.15,3757.00
3,2025-11-05,Customer 94,Cairo,Youssef,Electronics,Laptop,5,2313,0.15,9830.25
4,2025-08-31,Customer 54,Giza,Mona,Home,Lamp,7,2398,0.15,14268.10
5,2025-06-14,Customer 95,Giza,Sara,Electronics,Mouse,1,2073,0.15,1762.05
6,2025-11-16,Customer 101,Mansoura,Youssef,Home,Table,7,494,0.05,3285.10
7,2025-08-01,Customer 115,Cairo,Ahmed,Home,Lamp,6,676,0.10,3650.40
8,2025-10-07,Customer 15,Alex,Youssef,Clothes,Jacket,9,595,0.05,5087.25
9,2025-04-02,Customer 93,Alex,Sara,Home,Table,2,2325,0.15,3952.50

In [25]:
yo.iloc[:,6]

0       Chair
1       Pants
2        Lamp
3      Laptop
4        Lamp
        ...
495     Pants
496     Shirt
497     Table
498     Shirt
499    Laptop
Name: Product, Length: 500, dtype: object

# Merge = Join في سكوال

In [27]:
data1= pd.DataFrame({"Employe":["Emp1","Emp2","Emp3"], "Teams":["Team1","Team2","Team3"]})
data2=pd.DataFrame({"Employe":["Emp1","Emp2","Emp3"], "Hiring_Date":["2010","2020","2023"]})

In [29]:
data3=pd.merge(data1,data2)

In [30]:
data3

  Employe  Teams Hiring_Date
0    Emp1  Team1        2010
1    Emp2  Team2        2020
2    Emp3  Team3        2023

In [31]:
data4=pd.DataFrame({"Teams":["Team1","Team2","Team3"],"Salary":[30000,15000,12000]})

In [32]:
data5=pd.DataFrame({"Department":["Team1", "Team2", "Team3"], "Newsalary":[25000,20000,15000]})

In [33]:
Final_join=pd.merge(data4,data5,left_on="Teams",right_on="Department")

In [34]:
Final_join

   Teams  Salary Department  Newsalary
0  Team1   30000      Team1      25000
1  Team2   15000      Team2      20000
2  Team3   12000      Team3      15000

In [35]:
Final_join1=pd.merge(data4,data5)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [2]:
"D:\word\كشوفات المصروفات\Expenses July 2026\Total Expenses July 2026.docx"

'D:\\word\\كشوفات المصروفات\\Expenses July 2026\\Total Expenses July 2026.docx'

In [3]:
ss=pd.read_excel(r"D:\word\كشوفات المصروفات\Expenses July 2026\Total Expenses July 2026.docx")
ss

OptionError: No such keys(s): 'io.excel.zip.reader'

In [6]:
from docx import Document

doc = Document(r"D:\word\كشوفات المصروفات\Expenses July 2026\Total Expenses July 2026.docx")

for p in doc.paragraphs:
    print(p.text)

Total Expenses July 2026

July 1, 2026
Total of Nofrills = 47.11$
Total July 1, 2026 = 47.11$

July 3, 2026
Total of Nofrills = 60.43$
Total of Ever Green = 5.41$
Total of Dollar Tree = 16.54$
Total July 3, 2026 = 82.38$





July 5, 2026
Total of Dollarama = 10.50$
Total July 5, 2026 = 10.50$

July 7, 2026
Total of Damasus Butcher = 116.24$
Total of Dollar Tree = 6.00$
Total of Shawarma Palace- Forest lawn = 62.97$
Total July 7, 2026 = 185.21$

July 8, 2026
Total of Costco Wholesale club = 300.00$
Total of Wholesale club = 202.51$
Total July 8, 2026 = 502.51$

July 9, 2026
Total of Dollarama = 3.00$
Total July 9, 2026 = 3.00$





July 10, 2026
Total of Costco wholesale = 219.51$
Total of Calgary Wholesale = 55.79$
Total of Wholesale club = 156.50$
Total of Egyptian Market = 86.00$
Total of Dollarama = 10.88$
Total July 10, 2026 = 528.68$

July 14, 2026
Total of Costco Wholesale = 344.88$
Total July 14, 2026 = 344.88$

July 15, 2026
Total of Wholesale club = 181.46$
Total July 15, 2026 = 181.46$

July 16, 2026
Total of Nofrils= 21.95$
Total of Dollarama = 10.00$
Total July 16, 2026 = 31.95$

July 17, 2026
Total of Dollarama = 11.81$
Total July 17, 2026 = 11.81$

July 18, 2026
Total of Walmart = 22.00$
Total of Shawarma palace – Forest lawn = 22.00$
Total of July 18, 2026 = 44.00$

July 21, 2026
Total of Wholesale club = 175.65$
Total of July 21, 2026 = 175.65$

July 22, 2026
Total of Walmart = 6.00$
Total of Basha international Food = 48.32$
Total of Costco Wholesale = 214.83
Total of Wholesale Club = 93.33$
Total of July 22, 2026 = 362.48$


July 24, 2026
Total of Wholesale Club = 140.71$
Total July 24, 2026 = 140.71$

July 28, 2026
Total of Walmart = 16.69$
Total of Costco Wholesale = 408.39$
Total July 28, 2026 = 425.08$

July 30, 2026
Total of Nofrills = 61.00$
Total July 30, 2026 = 61.00$

Total from July 1, 2026 to July 30, 2026 = 3138.41$

In [5]:
!pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in c:\users\maged\anaconda3\lib\site-packages (from python-docx) (5.3.0)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\maged\anaconda3\lib\site-packages (from python-docx) (4.15.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0